# Generated by Django 3.0.3 on 2020-06-07 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('showcase_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('showcase_type', models.CharField(choices=[('A', 'Advertisement'), ('N', 'Normal'), ('P', 'Private Label'), ('R', 'Repair'), ('V', 'Vacant')], default='V', max_length=255)),
                ('rental_index', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('current_salary', models.DecimalField(decimal_places=1, max_digits=6)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('staff_type', models.CharField(choices=[('D', 'Director'), ('FTS', 'Full time staff'), ('HRM', 'Human resources manager'), ('IT', 'Part time staff'), ('PTS', 'Part time staff'), ('STM', 'Store manager')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=1, max_digits=6)),
                ('description', models.TextField(max_length=4096)),
                ('is_on_hold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('commission_rate', models.DecimalField(decimal_places=1, default=5, max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('showcase_index', models.PositiveIntegerField(default=0)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='server.Staff')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works_in', to='server.Store'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ShowcaseRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=1, max_digits=6)),
                ('remark', models.TextField(blank=True, max_length=4096, null=True)),
                ('showcase_type', models.CharField(choices=[('A', 'Advertisement'), ('N', 'Normal'), ('P', 'Private Label'), ('R', 'Repair'), ('V', 'Vacant')], default='N', max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Showcase')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='showcase',
            name='from_tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Tenant'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Store'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('grand_total', models.DecimalField(decimal_places=1, max_digits=6)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('tender', models.DecimalField(decimal_places=1, max_digits=6)),
                ('change', models.DecimalField(blank=True, decimal_places=1, max_digits=6)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=1, max_digits=6)),
                ('remark', models.TextField(max_length=4096)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Receipt')),
                ('stock_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=1, max_digits=6)),
                ('stock_in_qty', models.PositiveIntegerField()),
                ('remark', models.TextField(blank=True, max_length=4096, null=True)),
                ('from_showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Showcase')),
                ('from_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Stock')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('from_stock', 'from_showcase'), name='unique_stock_per_showcase'),
        ),
    ]
