# Generated by Django 3.0.3 on 2020-06-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_showcaserental_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='discount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
