# Generated by Django 3.0.3 on 2020-06-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20200610_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='stock_id',
            new_name='stock',
        ),
    ]
