# Generated by Django 3.0.3 on 2020-06-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20200610_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_id',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
