# Generated by Django 3.0.3 on 2020-06-11 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20200610_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='is_on_hold',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.Inventory'),
            preserve_default=False,
        ),
    ]
