# Generated by Django 3.0.3 on 2020-06-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_inventory_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='current_rent',
            field=models.DecimalField(decimal_places=1, default=600, max_digits=6),
        ),
    ]
