# Generated by Django 3.0.3 on 2020-05-28 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('showcase_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('current_salary', models.DecimalField(decimal_places=1, max_digits=6)),
                ('date_joined', models.DateField(max_length=255)),
                ('staff_type', models.CharField(choices=[('FTS', 'Full time staff'), ('HRM', 'Human resources manager'), ('IT', 'Part time staff'), ('PTS', 'Part time staff'), ('STM', 'Store manager')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('current_rent', models.DecimalField(decimal_places=1, max_digits=6)),
                ('description', models.TextField(max_length=4096)),
                ('is_on_hold', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('date_joined', models.DateField(max_length=255)),
                ('balance', models.DateField(max_length=255)),
                ('commission_rate', models.DecimalField(decimal_places=1, max_digits=6)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.Staff')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Store'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ShowcaseRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=1, max_digits=6)),
                ('remark', models.TextField(max_length=4096)),
                ('showcase_type', models.CharField(choices=[('N', 'Normal'), ('R', 'Repair'), ('A', 'Advertisement'), ('V', 'Vacant'), ('P', 'Private Label')], default='N', max_length=255)),
                ('showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Showcase')),
            ],
        ),
        migrations.AddField(
            model_name='showcase',
            name='from_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Tenant'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Store'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('grand_total', models.DecimalField(decimal_places=1, max_digits=6)),
                ('time', models.DateTimeField()),
                ('tender', models.DecimalField(decimal_places=1, max_digits=6)),
                ('change', models.DecimalField(decimal_places=1, max_digits=6)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=1, max_digits=6)),
                ('remark', models.TextField(max_length=4096)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Receipt')),
                ('stock_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=1, max_digits=6)),
                ('stock_in_qty', models.PositiveIntegerField()),
                ('remark', models.TextField(max_length=4096)),
                ('from_showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Showcase')),
                ('from_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Stock')),
            ],
        ),
    ]
