# Generated by Django 3.0.3 on 2020-05-28 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='store_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='store',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='works_in', to='server.Store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showcaserental',
            name='showcase_type',
            field=models.CharField(choices=[('V', 'Vacant'), ('R', 'Repair'), ('N', 'Normal'), ('P', 'Private Label'), ('A', 'Advertisement')], default='N', max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='server.Staff'),
        ),
    ]
