# Generated by Django 3.0.3 on 2020-05-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20200528_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcaserental',
            name='showcase_type',
            field=models.CharField(choices=[('V', 'Vacant'), ('A', 'Advertisement'), ('N', 'Normal'), ('P', 'Private Label'), ('R', 'Repair')], default='N', max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
