# Generated by Django 3.0.3 on 2020-05-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20200528_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcaserental',
            name='showcase_type',
            field=models.CharField(choices=[('A', 'Advertisement'), ('R', 'Repair'), ('V', 'Vacant'), ('P', 'Private Label'), ('N', 'Normal')], default='N', max_length=255),
        ),
    ]
