# Generated by Django 3.0.3 on 2020-06-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20200627_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
