# Generated by Django 3.0.3 on 2020-05-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20200528_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcaserental',
            name='showcase_type',
            field=models.CharField(choices=[('A', 'Advertisement'), ('N', 'Normal'), ('P', 'Private Label'), ('R', 'Repair'), ('V', 'Vacant')], default='N', max_length=255),
        ),
    ]
