# Generated by Django 3.0.3 on 2020-05-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20200528_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
