# Generated by Django 3.0.3 on 2020-05-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20200528_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='commission_rate',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=6),
        ),
    ]
