# Generated by Django 3.0.3 on 2020-05-31 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20200529_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='showcase_type',
            field=models.CharField(choices=[('A', 'Advertisement'), ('N', 'Normal'), ('P', 'Private Label'), ('R', 'Repair'), ('V', 'Vacant')], default='N', max_length=255),
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showcase',
            name='from_tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Tenant'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='showcase_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
