# Generated by Django 3.0.3 on 2020-06-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20200611_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('D', 'Director'), ('FTS', 'Full time staff'), ('HRM', 'Human resources manager'), ('IT', 'Accountant'), ('PTS', 'Part time staff'), ('STM', 'Store manager')], max_length=255),
        ),
    ]
