# Generated by Django 3.0.3 on 2020-06-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20200531_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='current_rent',
            new_name='unit_price',
        ),
    ]
