# Generated by Django 3.0.3 on 2020-06-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20200601_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('D', 'Director'), ('FTS', 'Full time staff'), ('HRM', 'Human resources manager'), ('IT', 'Part time staff'), ('PTS', 'Part time staff'), ('STM', 'Store manager')], max_length=255),
        ),
    ]
