# Generated by Django 3.0.3 on 2020-06-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20200601_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='showcase_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
