# Generated by Django 3.0.3 on 2020-06-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20200602_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='remark',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
