# Generated by Django 3.0.3 on 2020-06-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_auto_20200602_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='rental_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='showcaserental',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showcaserental',
            name='remark',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
