# Generated by Django 3.0.3 on 2020-06-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_auto_20200604_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaserental',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Tenant'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='showcase_type',
            field=models.CharField(choices=[('A', 'Advertisement'), ('N', 'Normal'), ('P', 'Private Label'), ('R', 'Repair'), ('V', 'Vacant')], default='V', max_length=255),
        ),
    ]
