# Generated by Django 3.0.3 on 2020-06-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_auto_20200606_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='is_on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
