# Generated by Django 3.0.3 on 2020-06-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_auto_20200606_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
